version: "3.9"
services:
  frontend:
    build:
      context: ./trading-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./trading-backend
    ports:
      - "8081:8081"
